# This name is currently not visible on GitHub due to
# https://github.com/actions/runner/issues/1877
name: Setup CI environment on Linux
description: Common part to tweak Linux CI runner environment
runs:
  using: composite
  steps:
    - name: Remove caches
      run: |
        df -h
        # https://github.com/actions/runner-images/blob/5a2cb18a48bce5da183486b95f5494e4fd0c0640/images/linux/scripts/installers/configure-environment.sh#L25-L29
        rm -rf "$AGENT_TOOLSDIRECTORY"
        rm -rf "/opt/hostedtoolcache"
      shell: bash
    - name: Listing 100 largest packages
      run: |
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
      shell: bash
    - name: Remove unnecessary packages
      run: |
        sudo apt-get remove -y '^aspnetcore-.*' --fix-missing
        sudo apt-get remove -y '^dotnet-.*' --fix-missing
        sudo apt-get remove -y '^mysql-.*' --fix-missing
        sudo apt-get remove -y 'php.*' --fix-missing
        sudo apt-get remove -y azure-cli --fix-missing
        sudo apt-get remove -y firefox --fix-missing
        sudo apt-get remove -y powershell --fix-missing
        sudo apt-get remove -y google-chrome-stable --fix-missing
        sudo apt-get remove -y google-cloud-cli --fix-missing
        sudo apt-get remove -y mono-devel --fix-missing
        sudo apt-get autoremove -y
        sudo apt-get clean
      shell: bash
    - name: Update APT cache
      run: |
        sudo apt -y update
        df -h
      shell: bash
