--[[
SPDX-License-Identifier: ISC
Copyright (c) 2023-2025, Sergey Bronnikov.

lua_createtable()

Creates a new empty table and pushes it onto the stack. The new
table has space pre-allocated for narr array elements and nrec
non-array elements. This pre-allocation is useful when you know
exactly how many elements the table will have.

http://www.lua.org/manual/5.1/manual.html
https://github.com/LuaJIT/LuaJIT/blob/8635cbabf3094c4d8bd00578c7d812bea87bb2d3/doc/extensions.html#L210-L216

Bad lookup generated by lj_record_idx in GC64,
https://github.com/LuaJIT/LuaJIT/issues/840

Synopsis: table.new(narray, nhash)
]]

local luzer = require("luzer")
local test_lib = require("lib")
local MAX_INT = test_lib.MAX_INT

-- PUC Rio Lua only.
if test_lib.lua_version() == "LuaJIT" then
    print("Unsupported version.")
    os.exit(0)
end

local function TestOneInput(buf)
    local fdp = luzer.FuzzedDataProvider(buf)
    local nhash = fdp:consume_integer(0, MAX_INT)
    local narray = fdp:consume_integer(0, MAX_INT)
    table.new(narray, nhash)
end

local args = {
    artifact_prefix = "table_new_",
}
luzer.Fuzz(TestOneInput, nil, args)
