# Batch Fuzzing ("batch").
# In batch fuzzing mode all fuzzers are run for a preset, longer, amount of time.
# Unlike in code change mode, batch fuzzing will not exit immediately upon
# discovering a bug. It will keep running other fuzzers until reaching the
# allotted fuzzing time.

name: Testing in ClusterFuzzLite (Batch)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/8 * * *'  # Every 8th hour.

permissions: read-all

jobs:
  luajit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - name: Build fuzzing tests (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run fuzzing tests (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          fuzz-seconds: 3600
          github-token: ${{ secrets.GITHUB_TOKEN }}
          minimize-crashes: true
          mode: 'batch'
          output-sarif: true
          parallel-fuzzing: true
          report-unreproducible-crashes: true
          sanitizer: ${{ matrix.sanitizer }}
          storage-repo-branch-coverage: gh-pages
          storage-repo-branch: cfl
          storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ligurio/lua-c-api-corpus
