name: Testing in ClusterFuzzLite (CI)

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: read-all

jobs:
  luajit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build fuzzing tests (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@main
        with:
          language: c
          sanitizer: ${{ matrix.sanitizer }}
          upload-build: true
