name: Testing in OSS Fuzz

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/**'
      - 'tests/**'
      - 'cmake/**'
  pull_request:
    types: [opened, reopened, synchronize, labeled]

concurrency:
  # Update of a developer branch cancels the previously scheduled workflow
  # run for this branch. However, the 'master' branch, and
  # tag workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow run ID' +
  # 'workflow run attempt' because it is a unique combination for any run.
  # So it effectively discards grouping.
  #
  # Important: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push event.
  group: ${{ (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/tags/')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  lua:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]

    steps:
      - name: Build fuzzing tests (${{ matrix.sanitizer }})
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: 'lua'
          dry-run: false
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run fuzzing tests (${{ matrix.sanitizer }})
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: 'lua'
          fuzz-seconds: 30
          dry-run: false
          sanitizer: ${{ matrix.sanitizer }}
